### ISSUE TITLE
Perhaps it is a mistake in task/serve.js

### ISSUE THREAD

**Issue by semernyakov** [VARIANTE/generator-vars-django#1]
## Old line

// gulp.watch(config.paths.tmp+'/*_/_.'+config.patterns.scripts, function() { sequence(browserSync.reload); });
## New line

gulp.watch(config.paths.src+'/*_/_.'+config.patterns.scripts, function() { sequence('scripts', browserSync.reload); });
## Result

Livereload work correct with js (try: gulp serve --debug --watch)

**Comment by andrewscwei** [comment]
Hey! Thanks for pointing this out. I took a closer look and realized that there was a mistake in the way run-sequence is used in that particular line. This is now fixed at 4f588245add0c500d297cbd3e097dd754d068d37.

The intention was to refresh the browser whenever JS files in the .tmp folder are changed and there is no need to explicitly run the 'scripts' task because that is handled by watchify.
