### ISSUE TITLE
Watching db.sqlite reloads on db save

### ISSUE THREAD

**Issue by rca** [VARIANTE/generator-vars-django#10]
I tracked down a problem where running a POST request where the database is saved would always reload the page.  This is due to `patterns.core` including `sqlite3` files when sqlite is being used in a project.  The line is https://github.com/andrewscwei/generator-vars-django/blob/master/app/templates/tasks/.taskconfig#L31

In my case, reloading the page on saving to the db is annoying at best, and at worst produces app behavior that's plain wrong.  Is there a use-case for watching the `sqlite3` database files?

**Comment by andrewscwei** [comment]
Thanks for the report. There isn't a use-case for watching the `sqlite3` file :) It was part of `patterns.core` to begin with because it needed to be copied over to the build directory in the `core` task. While I don't think it should produce any unintended app behavior in a production environment because you wouldn't be watching files with Gulp then, I definitely agree that it is horribly wrong to watch `sqlite3` files during development. That was unintended.

For the time being you can configure `tasks/.taskconfig` and change the watching entries for the `core` task. It's here:

``` js
...
watch: {
    entries: [{
      files: path.join(paths.src, '**', '*.' + patterns.core), // Modify this glob pattern(s), can be string or array
      tasks: ['core']
...
```

**Comment by andrewscwei** [comment]
v3.0.6 (433fcfa37e1e35c1959b6ed6edcbb0a9a58ae690) now has copying of db files as a separate task.
