### ISSUE TITLE
Best way to include glyphicon fonts from bootstrap?

### ISSUE THREAD

**Issue by jakobadam** [VARIANTE/generator-vars-django#8]
What's the best way to include fonts from a node module like bootstrap-sass?

Thanks.

kind regards,
Jakob

**Comment by andrewscwei** [comment]
`@import 'bootstrap-sass/assets/stylesheets/_bootstrap'`?

Or you just want the fonts from the `bootstrap-sass` package and maybe link to it later in runtime? Then you just need to somehow copy those fonts over to the build directory during the Gulp process.

One way to do it would be to tweak the config of the `fonts` task so that it also pipes `bootstrap-sass`'s fonts. In `tasks/.taskconfig`, add this to `module.exports.fonts.entry`:

``` js
...
fonts: {
  entry: [
    path.join(paths.src, 'static', 'fonts', '**', '*.' + patterns.fonts),
    path.join(__dirname, '../', 'node_modules/bootstrap-sass/assets/fonts/bootstrap/**/*'+patterns.fonts)
  ],
...
```

**Comment by jakobadam** [comment]
Exactly what I wanted to. 

In order to have the bootstrap css links match the font files I just had to change the path slightly.

```
path.join(__dirname, '../', 'node_modules/bootstrap-sass/assets/fonts', '**', '*.' + patterns.fonts)
```

Thanks a lot – gulp is new to me. So help much appreciated:)
